#!/bin/bash

# ============================================
# GUÍA RÁPIDA DE INICIO
# ============================================
# 
# Este archivo contiene instrucciones para 
# probar rápidamente el sistema de productos
# con WebSockets
#
# ============================================

echo "🚀 Sistema de Gestión de Productos con WebSockets"
echo "============================================"
echo ""
echo "📋 Pasos para ejecutar:"
echo ""
echo "1. Abre una terminal en este directorio"
echo ""
echo "2. Instala las dependencias (si no lo hiciste aún):"
echo "   npm install"
echo ""
echo "3. Inicia el servidor:"
echo "   npm start"
echo ""
echo "4. El servidor estará disponible en:"
echo "   http://localhost:3000"
echo ""
echo "5. Accede a las siguientes vistas:"
echo ""
echo "   📄 Vista Home (Catálogo Estático):"
echo "   http://localhost:3000/"
echo ""
echo "   ⚡ Vista Real-Time Products (con WebSockets):"
echo "   http://localhost:3000/realtimeproducts"
echo ""
echo "============================================"
echo "💡 PRUEBAS RECOMENDADAS:"
echo "============================================"
echo ""
echo "1. ✅ Abre /realtimeproducts en dos pestañas del navegador"
echo "2. ✅ Crea un nuevo producto en una pestaña"
echo "3. ✅ Observa cómo aparece automáticamente en la otra pestaña"
echo "4. ✅ Elimina un producto"
echo "5. ✅ Verifica que desaparece en ambas pestañas"
echo ""
echo "============================================"
echo "🔍 INFORMACIÓN TÉCNICA:"
echo "============================================"
echo ""
echo "📱 Puerto: 3000"
echo "📦 Framework: Express.js"
echo "🔄 Real-Time: Socket.io (WebSockets)"
echo "🎨 Motor de Plantillas: Handlebars"
echo "💾 Base de Datos: JSON Files"
echo ""
echo "============================================"
echo "📚 ARCHIVOS CLAVE:"
echo "============================================"
echo ""
echo "🟦 Servidor:"
echo "  src/server.js"
echo ""
echo "🟦 Managers:"
echo "  src/manager/Product.manager.js"
echo "  src/manager/Cart.manager.js"
echo ""
echo "🟦 WebSocket:"
echo "  src/socket/socketEvents.js"
echo ""
echo "🟦 Vistas:"
echo "  src/views/home.hbs"
echo "  src/views/realTimeProducts.hbs"
echo ""
echo "🟦 Cliente:"
echo "  public/js/realtimeProducts.js"
echo ""
echo "============================================"
echo ""
echo "¡Listo! Ejecuta 'npm start' para comenzar 🚀"
echo ""
